spring:
  application:
    name: ecom
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: 87654321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "1tssecret123456781tssecret123456781tssecret12345678"
  access:
    expiration: 900000
  refresh:
    expiration: 1800000
logging:
  level:
    root: INFO
ip-filter:
  allowed-ips: 127.0.0.1,192.168.1.1,0:0:0:0:0:0:0:1



